# YAML definition for travis-ci.com continuous integration.
# See https://docs.travis-ci.com/user/languages/c

language: c

compiler:
    - gcc

before_script:
    - mkdir build
    - cd build
    - CFLAGS='-g -O0 --coverage' cmake -G 'Unix Makefiles' ..

script:
    - make

after_success:
    - ../scripts/run-tests.sh
    - bash <(curl -s https://codecov.io/bash)
